export const GAME_CONFIG = {
	PIPE: {
		SPAWN_INTERVAL: 50,
		SPAWN_POINT_X: 2400,
		SPEED_X: -10,
		MIN_Y: 180,
		MAX_Y: 530,
		OFFSET_Y: 171,
		OBSTACLE_WIDTH_HALF: 60,
		GAP_SIZE_HALF: 230,
		COLLISION_RADIUS: 0,
		RETURN_TO_POOL_X: 0,
		GAP_MULTIPLIER: 2,
	},
	BUNNY: {
		GRAVITY: 2,
		JUMP_VELOCITY: -10,
		FORWARD_SPEED: 2,
		TARGET_X_MULTIPLIER: 0.5,
		INITIAL_X: 0,
		INITIAL_Y_MULTIPLIER: 0.5,
		INITIAL_X_SPEED: 0,
		INITIAL_Y_SPEED: 0,
		GRAVITY_MULTIPLIER: 0.1,
	},
	BACKGROUND: {
		SPEED_X: -10,
		CHECK_DISTANCE: 100,
		INITIAL_PIECES_EXTRA: 1,
		INITIAL_X: 0,
		SPRITE_INITIAL_X: 0,
	},
	SCENE: {
		INITIAL_SCORE: 0,
		GAME_OVER_ALPHA: 1,
	},
	COLLISION: {
		EPSILON: 0.01,
	},
} as const;

